// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCFtezlTplNVsQkcegitQyErXxTVckHG4',
    appId: '1:164168013727:web:0d49abfc8e2fbb21f18faa',
    messagingSenderId: '164168013727',
    projectId: 'lendiel-db1bc',
    authDomain: 'lendiel-db1bc.firebaseapp.com',
    storageBucket: 'lendiel-db1bc.appspot.com',
    measurementId: 'G-ER5HG50P8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MQGPO-zF6wgCe_v_LmML2aWanQ2tDiI',
    appId: '1:164168013727:android:f5270c1f67c54cb6f18faa',
    messagingSenderId: '164168013727',
    projectId: 'lendiel-db1bc',
    storageBucket: 'lendiel-db1bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1IL2PhM4-jiercQazmF0jSp6rC5msUaU',
    appId: '1:164168013727:ios:503c4bcbb5f95babf18faa',
    messagingSenderId: '164168013727',
    projectId: 'lendiel-db1bc',
    storageBucket: 'lendiel-db1bc.appspot.com',
    iosClientId:
        '164168013727-fcpjt67rkkfl005vfa4gi5cv161d817c.apps.googleusercontent.com',
    iosBundleId: 'ua.lendi.checker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1IL2PhM4-jiercQazmF0jSp6rC5msUaU',
    appId: '1:164168013727:ios:779d99fe09702955f18faa',
    messagingSenderId: '164168013727',
    projectId: 'lendiel-db1bc',
    storageBucket: 'lendiel-db1bc.appspot.com',
    iosClientId:
        '164168013727-k4p0bc4reh70ns9egtcg3j6ng30imkn5.apps.googleusercontent.com',
    iosBundleId: 'ua.lendi.checker.RunnerTests',
  );
}
